version: '3'
services:
  postgres:
    image: postgres:alpine
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    environment: 
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
  app:
    image: panchem/voter
    build: .
    environment:
      DATABASE: postgres
      POSTGRES_CONNECTION_STRING: "host=postgres port=5432 user=postgres dbname=postgres password=password sslmode=disable"
    labels:
      - "traefik.backend=be"
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:${HOST_URL}"
      - "traefik.default.protocol=http"
      - "traefik.frontend.priority=20"
networks:
  default:
    external:
      name: proxy
