version: '3'
services:
  postgres:
    image: postgres:alpine
    volumes:
      - "/postgres:/var/lib/postgresql/data"
    environment: 
      POSTGRES_PASSWORD: voterpassword
      POSTGRES_USER: voter
      POSTGRES_DB: voter
  app:
    image: panchem/voter
    build: .
    restart: on-failure
    depends_on:
      - postgres
    labels:
      - "traefik.backend=be"
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.port=4000"
      - "traefik.frontend.rule=Host:${HOST_URL}"
      - "traefik.default.protocol=http"
      - "traefik.frontend.priority=20"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentSecurityPolicy=frame-ancestors 'none'; default-src https:; object-src 'none'; img-src * data:; script-src 'self' cdn.auth0.com; style-src 'self' 'unsafe-inline'"
networks:
  default:
    external:
      name: proxy
