version: '3'
services:
  postgres:
    image: postgres:alpine
    environment: 
      POSTGRES_PASSWORD: voterpassword
      POSTGRES_USER: voter
      POSTGRES_DB: voter
    volumes:
      - "./postgres:/var/lib/postgresql/data"
  app:
    image: panchem/voter
    build: .
    restart: on-failure
    ports:
      - "8080:4000"