version: '3'
services:
  postgres:
    image: postgres:alpine
    environment: 
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
  app:
    image: panchem/voter
    build: .
    environment: 
      PORT: 8080
    labels:
      - "traefik.backend=be"
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:vote.panchem.io"
      - "traefik.default.protocol=http"
      - "traefik.frontend.priority=20"