version: '3'
services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: voterpassword
      POSTGRES_USER: voter
      POSTGRES_DB: voter
  adminer:
    image: adminer
    ports:
      - 9000:8080