scalar Date

type Query {
  subjects: [Subject]!
  subject(id: ID!): Subject!
}

type Mutation {
  createSubject(input: SubjectCreation!): Subject!
  vote(subjectId: ID!): Vote!
}

type Subject {
  id: ID!
  personName: String!
  costumeDescription: String!
  votes: [Vote!]!
  history: [SubjectHistory!]!
  createdAt: Date!
  updatedAt: Date!
}

type SubjectHistory {
  id: ID!
  editor: User!
  personName: String!
  costumeDescription: String!
  subject: Subject!
  createdAt: Date!
  updatedAt: Date!
}

type User {
  id: ID!
  name: String!
  banned: Boolean!
  admin: Boolean!
  createdAt: Date!
  updatedAt: Date!
}

type Vote {
  id: ID!
  voter: User!
  subject: Subject!
  createdAt: Date!
  updatedAt: Date!
}

input SubjectCreation {
  personName: String!
  costumeDescription: String!
}
